#include <stdint.h>
/* Generated by mkromfs. Edit with caution. */
#include <rtthread.h>
#include <dfs_romfs.h>

static const struct romfs_dirent _romfs_root_flash0[] = {

};

static const struct romfs_dirent _romfs_root_flash1[] = {

};

static const struct romfs_dirent _romfs_root_sd[] = {

};

static const struct romfs_dirent _romfs_root_udisk[] = {

};

static const struct romfs_dirent _romfs_root[] = {
    {ROMFS_DIRENT_DIR, "flash0", (uint8_t *)_romfs_root_flash0, sizeof(_romfs_root_flash0)/sizeof(_romfs_root_flash0[0])},
    {ROMFS_DIRENT_DIR, "flash1", (uint8_t *)_romfs_root_flash1, sizeof(_romfs_root_flash1)/sizeof(_romfs_root_flash1[0])},
    {ROMFS_DIRENT_DIR, "sd", (uint8_t *)_romfs_root_sd, sizeof(_romfs_root_sd)/sizeof(_romfs_root_sd[0])},
    {ROMFS_DIRENT_DIR, "udisk", (uint8_t *)_romfs_root_udisk, sizeof(_romfs_root_udisk)/sizeof(_romfs_root_udisk[0])}
};

const struct romfs_dirent romfs_root = {
    ROMFS_DIRENT_DIR, "/", (uint8_t *)_romfs_root, sizeof(_romfs_root)/sizeof(_romfs_root[0])
};
